const dashboardData = {
  vacation: {
    overview: [
      {
        title: "Occupancy Rate",
        amount: "72.3%",
        improve: "+4.1% from last month",
        icon: "/img/dashboard/icons/1.svg",
        description: "Percentage of nights booked",
      },
      {
        title: "Avg Length of Stay",
        amount: "4.2 days",
        improve: "+0.5 days from last month",
        icon: "/img/dashboard/icons/3.svg",
        description: "Average duration of guest stays",
      },
      {
        title: "Net Revenue",
        amount: "$18,565.00",
        improve: "+12.6% from last month",
        icon: "/img/dashboard/icons/2.svg",
        description: "Revenue after fees and expenses",
      },
      {
        title: "Booking Window",
        amount: "38 days",
        improve: "+5 days from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Average time between booking and check-in",
      },
    ],
    analytics: [
      {
        title: "Total bookings",
        amount: "1000",
        improve: "+4.1% from last month",
        icon: "/img/dashboard/icons/1.svg",
        description: "Track bookings by category to identify high-demand services.",
      },
      {
        title: "Commission earned",
        amount: "$10,000 in Q1",
        improve: "+0.5% from last month",
        icon: "/img/dashboard/icons/3.svg",
        description: "Measure the earnings from commissions.",
      },
      {
        title: "Conversion rate",
        amount: "20%",
        improve: "+12.6% from last month",
        icon: "/img/dashboard/icons/2.svg",
        description: "Monitor the effectiveness of sales efforts.",
      },
      {
        title: "Customer retention",
        amount: "70%",
        improve: "+2% from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Track customer loyalty to improve service offerings.",
      },
      {
        title: "Upsell/cross-sell success",
        amount: "30%",
        improve: "+0.5% from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Evaluate the effectiveness of upsell and cross-sell strategies.",
      },
    ],
    reports: [
      {
        title: "Agent performance leaderboard",
        amount: "Agent A",
        improve: "+12% from last quarter",
        icon: "/img/dashboard/icons/1.svg",
        description:
          "Compare agent performance to identify best practices.",
      },
      {
        title: "Sales by region/service",
        amount: "Highest sales in North America",
        improve: "↑25% bookings vs. winter",
        icon: "/img/dashboard/icons/2.svg",
        description: "Identify high-performing regions and services.",
      },
      {
        title: "Customer feedback summary",
        amount: "4.5 avg rating from 100 reviews",
        improve: "-3% from last quarter",
        icon: "/img/dashboard/icons/3.svg",
        description:
          "Monitor customer feedback to improve service quality.",
      },
      {
        title: "Booking trends by season",
        amount: "Higher bookings in summer",
        improve: "+8% from last quarter",
        icon: "/img/dashboard/icons/4.svg",
        description: "Plan for seasonal variations in demand.",
      },
      {
        title: "Revenue vs. target",
        amount: "Achieved 90% of revenue target in Q1",
        improve: "+8% from last quarter",
        icon: "/img/dashboard/icons/4.svg",
        description: "Measure performance against revenue targets.",
      },
    ],
  },
  spaces: {
    overview: [
      {
        title: "Venue Occupancy",
        amount: "65.8%",
        improve: "+7.3% from last month",
        icon: "/img/dashboard/icons/1.svg",
        description: "Percentage of time venue is booked",
      },
      {
        title: "Event Bookings",
        amount: "22",
        improve: "+4 from last month",
        icon: "/img/dashboard/icons/3.svg",
        description: "Number of events booked",
      },
      {
        title: "Avg Revenue/Event",
        amount: "$1,250.00",
        improve: "+5.2% from last month",
        icon: "/img/dashboard/icons/2.svg",
        description: "Average revenue per event",
      },
      {
        title: "Customer Retention",
        amount: "68.5%",
        improve: "+3.1% from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Percentage of repeat customers",
      },
    ],
    analytics: [
      {
        title: "Total bookings",
        amount: "1000",
        improve: "+4.1% from last month",
        icon: "/img/dashboard/icons/1.svg",
        description: "Track bookings by category to identify high-demand services.",
      },
      {
        title: "Commission earned",
        amount: "$10,000 in Q1",
        improve: "+0.5% from last month",
        icon: "/img/dashboard/icons/3.svg",
        description: "Measure the earnings from commissions.",
      },
      {
        title: "Conversion rate",
        amount: "20%",
        improve: "+12.6% from last month",
        icon: "/img/dashboard/icons/2.svg",
        description: "Monitor the effectiveness of sales efforts.",
      },
      {
        title: "Customer retention",
        amount: "70%",
        improve: "+2% from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Track customer loyalty to improve service offerings.",
      },
      {
        title: "Upsell/cross-sell success",
        amount: "30%",
        improve: "+0.5% from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Evaluate the effectiveness of upsell and cross-sell strategies.",
      },
    ],
    reports: [
      {
        title: "Agent performance leaderboard",
        amount: "Agent A",
        improve: "+12% from last quarter",
        icon: "/img/dashboard/icons/1.svg",
        description:
          "Compare agent performance to identify best practices.",
      },
      {
        title: "Sales by region/service",
        amount: "Highest sales in North America",
        improve: "↑25% bookings vs. winter",
        icon: "/img/dashboard/icons/2.svg",
        description: "Identify high-performing regions and services.",
      },
      {
        title: "Customer feedback summary",
        amount: "4.5 avg rating from 100 reviews",
        improve: "-3% from last quarter",
        icon: "/img/dashboard/icons/3.svg",
        description:
          "Monitor customer feedback to improve service quality.",
      },
      {
        title: "Booking trends by season",
        amount: "Higher bookings in summer",
        improve: "+8% from last quarter",
        icon: "/img/dashboard/icons/4.svg",
        description: "Plan for seasonal variations in demand.",
      },
      {
        title: "Revenue vs. target",
        amount: "Achieved 90% of revenue target in Q1",
        improve: "+8% from last quarter",
        icon: "/img/dashboard/icons/4.svg",
        description: "Measure performance against revenue targets.",
      },
    ],
  },
  activity: {
    overview: [
      {
        title: "Conversion Rate",
        amount: "9.3%",
        improve: "+2.1% from last month",
        icon: "/img/dashboard/icons/1.svg",
        description: "Percentage of visitors who book",
      },
      {
        title: "Attendance Rate",
        amount: "91.2%",
        improve: "+2.8% from last month",
        icon: "/img/dashboard/icons/3.svg",
        description: "Percentage of booked spots attended",
      },
      {
        title: "Revenue/Activity",
        amount: "$420.00",
        improve: "+5.7% from last month",
        icon: "/img/dashboard/icons/2.svg",
        description: "Average revenue per activity",
      },
      {
        title: "Avg Rating",
        amount: "4.8/5",
        improve: "+0.3 from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Average customer rating",
      },
    ],
    analytics: [
      {
        title: "Total bookings",
        amount: "1000",
        improve: "+4.1% from last month",
        icon: "/img/dashboard/icons/1.svg",
        description: "Track bookings by category to identify high-demand services.",
      },
      {
        title: "Commission earned",
        amount: "$10,000 in Q1",
        improve: "+0.5% from last month",
        icon: "/img/dashboard/icons/3.svg",
        description: "Measure the earnings from commissions.",
      },
      {
        title: "Conversion rate",
        amount: "20%",
        improve: "+12.6% from last month",
        icon: "/img/dashboard/icons/2.svg",
        description: "Monitor the effectiveness of sales efforts.",
      },
      {
        title: "Customer retention",
        amount: "70%",
        improve: "+2% from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Track customer loyalty to improve service offerings.",
      },
      {
        title: "Upsell/cross-sell success",
        amount: "30%",
        improve: "+0.5% from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Evaluate the effectiveness of upsell and cross-sell strategies.",
      },
    ],
    reports: [
      {
        title: "Agent performance leaderboard",
        amount: "Agent A",
        improve: "+12% from last quarter",
        icon: "/img/dashboard/icons/1.svg",
        description:
          "Compare agent performance to identify best practices.",
      },
      {
        title: "Sales by region/service",
        amount: "Highest sales in North America",
        improve: "↑25% bookings vs. winter",
        icon: "/img/dashboard/icons/2.svg",
        description: "Identify high-performing regions and services.",
      },
      {
        title: "Customer feedback summary",
        amount: "4.5 avg rating from 100 reviews",
        improve: "-3% from last quarter",
        icon: "/img/dashboard/icons/3.svg",
        description:
          "Monitor customer feedback to improve service quality.",
      },
      {
        title: "Booking trends by season",
        amount: "Higher bookings in summer",
        improve: "+8% from last quarter",
        icon: "/img/dashboard/icons/4.svg",
        description: "Plan for seasonal variations in demand.",
      },
      {
        title: "Revenue vs. target",
        amount: "Achieved 90% of revenue target in Q1",
        improve: "+8% from last quarter",
        icon: "/img/dashboard/icons/4.svg",
        description: "Measure performance against revenue targets.",
      },
    ],
  },
  event: {
    overview: [
      {
        title: "Venue Occupancy",
        amount: "65.8%",
        improve: "+7.3% from last month",
        icon: "/img/dashboard/icons/1.svg",
        description: "Percentage of time venue is booked",
      },
      {
        title: "Event Bookings",
        amount: "22",
        improve: "+4 from last month",
        icon: "/img/dashboard/icons/3.svg",
        description: "Number of events booked",
      },
      {
        title: "Avg Revenue/Event",
        amount: "$1,250.00",
        improve: "+5.2% from last month",
        icon: "/img/dashboard/icons/2.svg",
        description: "Average revenue per event",
      },
      {
        title: "Customer Retention",
        amount: "68.5%",
        improve: "+3.1% from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Percentage of repeat customers",
      },
    ],
    analytics: [
      {
        title: "Total bookings",
        amount: "1000",
        improve: "+4.1% from last month",
        icon: "/img/dashboard/icons/1.svg",
        description: "Track bookings by category to identify high-demand services.",
      },
      {
        title: "Commission earned",
        amount: "$10,000 in Q1",
        improve: "+0.5% from last month",
        icon: "/img/dashboard/icons/3.svg",
        description: "Measure the earnings from commissions.",
      },
      {
        title: "Conversion rate",
        amount: "20%",
        improve: "+12.6% from last month",
        icon: "/img/dashboard/icons/2.svg",
        description: "Monitor the effectiveness of sales efforts.",
      },
      {
        title: "Customer retention",
        amount: "70%",
        improve: "+2% from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Track customer loyalty to improve service offerings.",
      },
      {
        title: "Upsell/cross-sell success",
        amount: "30%",
        improve: "+0.5% from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Evaluate the effectiveness of upsell and cross-sell strategies.",
      },
    ],
    reports: [
      {
        title: "Agent performance leaderboard",
        amount: "Agent A",
        improve: "+12% from last quarter",
        icon: "/img/dashboard/icons/1.svg",
        description:
          "Compare agent performance to identify best practices.",
      },
      {
        title: "Sales by region/service",
        amount: "Highest sales in North America",
        improve: "↑25% bookings vs. winter",
        icon: "/img/dashboard/icons/2.svg",
        description: "Identify high-performing regions and services.",
      },
      {
        title: "Customer feedback summary",
        amount: "4.5 avg rating from 100 reviews",
        improve: "-3% from last quarter",
        icon: "/img/dashboard/icons/3.svg",
        description:
          "Monitor customer feedback to improve service quality.",
      },
      {
        title: "Booking trends by season",
        amount: "Higher bookings in summer",
        improve: "+8% from last quarter",
        icon: "/img/dashboard/icons/4.svg",
        description: "Plan for seasonal variations in demand.",
      },
      {
        title: "Revenue vs. target",
        amount: "Achieved 90% of revenue target in Q1",
        improve: "+8% from last quarter",
        icon: "/img/dashboard/icons/4.svg",
        description: "Measure performance against revenue targets.",
      },
    ],
  },
  venue: {
    overview: [
      {
        title: "Venue Occupancy",
        amount: "65.8%",
        improve: "+7.3% from last month",
        icon: "/img/dashboard/icons/1.svg",
        description: "Percentage of time venue is booked",
      },
      {
        title: "Event Bookings",
        amount: "22",
        improve: "+4 from last month",
        icon: "/img/dashboard/icons/3.svg",
        description: "Number of events booked",
      },
      {
        title: "Avg Revenue/Event",
        amount: "$1,250.00",
        improve: "+5.2% from last month",
        icon: "/img/dashboard/icons/2.svg",
        description: "Average revenue per event",
      },
      {
        title: "Customer Retention",
        amount: "68.5%",
        improve: "+3.1% from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Percentage of repeat customers",
      },
    ],
    analytics: [
      {
        title: "Total bookings",
        amount: "1000",
        improve: "+4.1% from last month",
        icon: "/img/dashboard/icons/1.svg",
        description: "Track bookings by category to identify high-demand services.",
      },
      {
        title: "Commission earned",
        amount: "$10,000 in Q1",
        improve: "+0.5% from last month",
        icon: "/img/dashboard/icons/3.svg",
        description: "Measure the earnings from commissions.",
      },
      {
        title: "Conversion rate",
        amount: "20%",
        improve: "+12.6% from last month",
        icon: "/img/dashboard/icons/2.svg",
        description: "Monitor the effectiveness of sales efforts.",
      },
      {
        title: "Customer retention",
        amount: "70%",
        improve: "+2% from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Track customer loyalty to improve service offerings.",
      },
      {
        title: "Upsell/cross-sell success",
        amount: "30%",
        improve: "+0.5% from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Evaluate the effectiveness of upsell and cross-sell strategies.",
      },
    ],
    reports: [
      {
        title: "Agent performance leaderboard",
        amount: "Agent A",
        improve: "+12% from last quarter",
        icon: "/img/dashboard/icons/1.svg",
        description:
          "Compare agent performance to identify best practices.",
      },
      {
        title: "Sales by region/service",
        amount: "Highest sales in North America",
        improve: "↑25% bookings vs. winter",
        icon: "/img/dashboard/icons/2.svg",
        description: "Identify high-performing regions and services.",
      },
      {
        title: "Customer feedback summary",
        amount: "4.5 avg rating from 100 reviews",
        improve: "-3% from last quarter",
        icon: "/img/dashboard/icons/3.svg",
        description:
          "Monitor customer feedback to improve service quality.",
      },
      {
        title: "Booking trends by season",
        amount: "Higher bookings in summer",
        improve: "+8% from last quarter",
        icon: "/img/dashboard/icons/4.svg",
        description: "Plan for seasonal variations in demand.",
      },
      {
        title: "Revenue vs. target",
        amount: "Achieved 90% of revenue target in Q1",
        improve: "+8% from last quarter",
        icon: "/img/dashboard/icons/4.svg",
        description: "Measure performance against revenue targets.",
      },
    ],
  },
  hotel: {
    overview: [
      {
        title: "Occupancy Rate",
        amount: "78.5%",
        improve: "+5.2% from last month",
        icon: "/img/dashboard/icons/1.svg",
        description: "Percentage of available rooms occupied",
      },
      {
        title: "Average Daily Rate",
        amount: "$189.50",
        improve: "+3.8% from last month",
        icon: "/img/dashboard/icons/3.svg",
        description: "Average revenue per occupied room",
      },
      {
        title: "RevPAR",
        amount: "$148.75",
        improve: "+9.1% from last month",
        icon: "/img/dashboard/icons/2.svg",
        description: "Revenue per available room",
      },
      {
        title: "Average Rating",
        amount: "4.7/5",
        improve: "+0.2 from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Average customer rating",
      },
    ],
    analytics: [
      {
        title: "Total bookings",
        amount: "1000",
        improve: "+4.1% from last month",
        icon: "/img/dashboard/icons/1.svg",
        description: "Track bookings by category to identify high-demand services.",
      },
      {
        title: "Commission earned",
        amount: "$10,000 in Q1",
        improve: "+0.5% from last month",
        icon: "/img/dashboard/icons/3.svg",
        description: "Measure the earnings from commissions.",
      },
      {
        title: "Conversion rate",
        amount: "20%",
        improve: "+12.6% from last month",
        icon: "/img/dashboard/icons/2.svg",
        description: "Monitor the effectiveness of sales efforts.",
      },
      {
        title: "Customer retention",
        amount: "70%",
        improve: "+2% from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Track customer loyalty to improve service offerings.",
      },
      {
        title: "Upsell/cross-sell success",
        amount: "30%",
        improve: "+0.5% from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Evaluate the effectiveness of upsell and cross-sell strategies.",
      },
    ],
    reports: [
      {
        title: "Agent performance leaderboard",
        amount: "Agent A",
        improve: "+12% from last quarter",
        icon: "/img/dashboard/icons/1.svg",
        description:
          "Compare agent performance to identify best practices.",
      },
      {
        title: "Sales by region/service",
        amount: "Highest sales in North America",
        improve: "↑25% bookings vs. winter",
        icon: "/img/dashboard/icons/2.svg",
        description: "Identify high-performing regions and services.",
      },
      {
        title: "Customer feedback summary",
        amount: "4.5 avg rating from 100 reviews",
        improve: "-3% from last quarter",
        icon: "/img/dashboard/icons/3.svg",
        description:
          "Monitor customer feedback to improve service quality.",
      },
      {
        title: "Booking trends by season",
        amount: "Higher bookings in summer",
        improve: "+8% from last quarter",
        icon: "/img/dashboard/icons/4.svg",
        description: "Plan for seasonal variations in demand.",
      },
      {
        title: "Revenue vs. target",
        amount: "Achieved 90% of revenue target in Q1",
        improve: "+8% from last quarter",
        icon: "/img/dashboard/icons/4.svg",
        description: "Measure performance against revenue targets.",
      },
    ],
  },
  tour: {
    overview: [
      {
        title: "Conversion Rate",
        amount: "8.7%",
        improve: "+1.2% from last month",
        icon: "/img/dashboard/icons/1.svg",
        description: "Percentage of visitors who book",
      },
      {
        title: "Occupancy Rate",
        amount: "82.4%",
        improve: "+6.5% from last month",
        icon: "/img/dashboard/icons/3.svg",
        description: "Percentage of tour spots booked",
      },
      {
        title: "Revenue per Tour",
        amount: "$560.00",
        improve: "+4.8% from last month",
        icon: "/img/dashboard/icons/2.svg",
        description: "Average revenue per tour",
      },
      {
        title: "Cancellation Rate",
        amount: "4.2%",
        improve: "-1.5% from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Percentage of tours canceled",
      },
    ],
    analytics: [
      {
        title: "Total bookings",
        amount: "1000",
        improve: "+4.1% from last month",
        icon: "/img/dashboard/icons/1.svg",
        description: "Track bookings by category to identify high-demand services.",
      },
      {
        title: "Commission earned",
        amount: "$10,000 in Q1",
        improve: "+0.5% from last month",
        icon: "/img/dashboard/icons/3.svg",
        description: "Measure the earnings from commissions.",
      },
      {
        title: "Conversion rate",
        amount: "20%",
        improve: "+12.6% from last month",
        icon: "/img/dashboard/icons/2.svg",
        description: "Monitor the effectiveness of sales efforts.",
      },
      {
        title: "Customer retention",
        amount: "70%",
        improve: "+2% from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Track customer loyalty to improve service offerings.",
      },
      {
        title: "Upsell/cross-sell success",
        amount: "30%",
        improve: "+0.5% from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Evaluate the effectiveness of upsell and cross-sell strategies.",
      },
    ],
    reports: [
      {
        title: "Agent performance leaderboard",
        amount: "Agent A",
        improve: "+12% from last quarter",
        icon: "/img/dashboard/icons/1.svg",
        description:
          "Compare agent performance to identify best practices.",
      },
      {
        title: "Sales by region/service",
        amount: "Highest sales in North America",
        improve: "↑25% bookings vs. winter",
        icon: "/img/dashboard/icons/2.svg",
        description: "Identify high-performing regions and services.",
      },
      {
        title: "Customer feedback summary",
        amount: "4.5 avg rating from 100 reviews",
        improve: "-3% from last quarter",
        icon: "/img/dashboard/icons/3.svg",
        description:
          "Monitor customer feedback to improve service quality.",
      },
      {
        title: "Booking trends by season",
        amount: "Higher bookings in summer",
        improve: "+8% from last quarter",
        icon: "/img/dashboard/icons/4.svg",
        description: "Plan for seasonal variations in demand.",
      },
      {
        title: "Revenue vs. target",
        amount: "Achieved 90% of revenue target in Q1",
        improve: "+8% from last quarter",
        icon: "/img/dashboard/icons/4.svg",
        description: "Measure performance against revenue targets.",
      },
    ],
  },
  rides: {
    overview: [
      {
        title: "Venue Occupancy",
        amount: "65.8%",
        improve: "+7.3% from last month",
        icon: "/img/dashboard/icons/1.svg",
        description: "Percentage of time venue is booked",
      },
      {
        title: "Event Bookings",
        amount: "22",
        improve: "+4 from last month",
        icon: "/img/dashboard/icons/3.svg",
        description: "Number of events booked",
      },
      {
        title: "Avg Revenue/Event",
        amount: "$1,250.00",
        improve: "+5.2% from last month",
        icon: "/img/dashboard/icons/2.svg",
        description: "Average revenue per event",
      },
      {
        title: "Customer Retention",
        amount: "68.5%",
        improve: "+3.1% from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Percentage of repeat customers",
      },
    ],
    analytics: [
      {
        title: "Total bookings",
        amount: "1000",
        improve: "+4.1% from last month",
        icon: "/img/dashboard/icons/1.svg",
        description: "Track bookings by category to identify high-demand services.",
      },
      {
        title: "Commission earned",
        amount: "$10,000 in Q1",
        improve: "+0.5% from last month",
        icon: "/img/dashboard/icons/3.svg",
        description: "Measure the earnings from commissions.",
      },
      {
        title: "Conversion rate",
        amount: "20%",
        improve: "+12.6% from last month",
        icon: "/img/dashboard/icons/2.svg",
        description: "Monitor the effectiveness of sales efforts.",
      },
      {
        title: "Customer retention",
        amount: "70%",
        improve: "+2% from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Track customer loyalty to improve service offerings.",
      },
      {
        title: "Upsell/cross-sell success",
        amount: "30%",
        improve: "+0.5% from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Evaluate the effectiveness of upsell and cross-sell strategies.",
      },
    ],
    reports: [
      {
        title: "Agent performance leaderboard",
        amount: "Agent A",
        improve: "+12% from last quarter",
        icon: "/img/dashboard/icons/1.svg",
        description:
          "Compare agent performance to identify best practices.",
      },
      {
        title: "Sales by region/service",
        amount: "Highest sales in North America",
        improve: "↑25% bookings vs. winter",
        icon: "/img/dashboard/icons/2.svg",
        description: "Identify high-performing regions and services.",
      },
      {
        title: "Customer feedback summary",
        amount: "4.5 avg rating from 100 reviews",
        improve: "-3% from last quarter",
        icon: "/img/dashboard/icons/3.svg",
        description:
          "Monitor customer feedback to improve service quality.",
      },
      {
        title: "Booking trends by season",
        amount: "Higher bookings in summer",
        improve: "+8% from last quarter",
        icon: "/img/dashboard/icons/4.svg",
        description: "Plan for seasonal variations in demand.",
      },
      {
        title: "Revenue vs. target",
        amount: "Achieved 90% of revenue target in Q1",
        improve: "+8% from last quarter",
        icon: "/img/dashboard/icons/4.svg",
        description: "Measure performance against revenue targets.",
      },
    ],
  },
  flights: {
    overview: [
      {
        title: "Venue Occupancy",
        amount: "65.8%",
        improve: "+7.3% from last month",
        icon: "/img/dashboard/icons/1.svg",
        description: "Percentage of time venue is booked",
      },
      {
        title: "Event Bookings",
        amount: "22",
        improve: "+4 from last month",
        icon: "/img/dashboard/icons/3.svg",
        description: "Number of events booked",
      },
      {
        title: "Avg Revenue/Event",
        amount: "$1,250.00",
        improve: "+5.2% from last month",
        icon: "/img/dashboard/icons/2.svg",
        description: "Average revenue per event",
      },
      {
        title: "Customer Retention",
        amount: "68.5%",
        improve: "+3.1% from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Percentage of repeat customers",
      },
    ],
    analytics: [
      {
        title: "Total bookings",
        amount: "1000",
        improve: "+4.1% from last month",
        icon: "/img/dashboard/icons/1.svg",
        description: "Track bookings by category to identify high-demand services.",
      },
      {
        title: "Commission earned",
        amount: "$10,000 in Q1",
        improve: "+0.5% from last month",
        icon: "/img/dashboard/icons/3.svg",
        description: "Measure the earnings from commissions.",
      },
      {
        title: "Conversion rate",
        amount: "20%",
        improve: "+12.6% from last month",
        icon: "/img/dashboard/icons/2.svg",
        description: "Monitor the effectiveness of sales efforts.",
      },
      {
        title: "Customer retention",
        amount: "70%",
        improve: "+2% from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Track customer loyalty to improve service offerings.",
      },
      {
        title: "Upsell/cross-sell success",
        amount: "30%",
        improve: "+0.5% from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Evaluate the effectiveness of upsell and cross-sell strategies.",
      },
    ],
    reports: [
      {
        title: "Agent performance leaderboard",
        amount: "Agent A",
        improve: "+12% from last quarter",
        icon: "/img/dashboard/icons/1.svg",
        description:
          "Compare agent performance to identify best practices.",
      },
      {
        title: "Sales by region/service",
        amount: "Highest sales in North America",
        improve: "↑25% bookings vs. winter",
        icon: "/img/dashboard/icons/2.svg",
        description: "Identify high-performing regions and services.",
      },
      {
        title: "Customer feedback summary",
        amount: "4.5 avg rating from 100 reviews",
        improve: "-3% from last quarter",
        icon: "/img/dashboard/icons/3.svg",
        description:
          "Monitor customer feedback to improve service quality.",
      },
      {
        title: "Booking trends by season",
        amount: "Higher bookings in summer",
        improve: "+8% from last quarter",
        icon: "/img/dashboard/icons/4.svg",
        description: "Plan for seasonal variations in demand.",
      },
      {
        title: "Revenue vs. target",
        amount: "Achieved 90% of revenue target in Q1",
        improve: "+8% from last quarter",
        icon: "/img/dashboard/icons/4.svg",
        description: "Measure performance against revenue targets.",
      },
    ],
  },
};

export default dashboardData;
