const dashboardData = {
  vacation: {
    overview: [
      {
        title: "Occupancy Rate",
        amount: "72.3%",
        improve: "+4.1% from last month",
        icon: "/img/dashboard/icons/1.svg",
        description: "Percentage of nights booked",
      },
      {
        title: "Avg Length of Stay",
        amount: "4.2 days",
        improve: "+0.5 days from last month",
        icon: "/img/dashboard/icons/3.svg",
        description: "Average duration of guest stays",
      },
      {
        title: "Net Revenue",
        amount: "$18,565.00",
        improve: "+12.6% from last month",
        icon: "/img/dashboard/icons/2.svg",
        description: "Revenue after fees and expenses",
      },
      {
        title: "Booking Window",
        amount: "38 days",
        improve: "+5 days from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Average time between booking and check-in",
      },
    ],
    analytics: [
      {
        title: "Occupancy Rate",
        amount: "75%",
        improve: "+3.2% from last month",
        icon: "/img/dashboard/icons/1.svg",
        description:
          "Higher occupancy indicates better utilization of properties.",
      },
      {
        title: "Average Nightly Rate",
        amount: "$150",
        improve: "+5.1% from last month",
        icon: "/img/dashboard/icons/2.svg",
        description: "Track pricing to ensure competitiveness.",
      },
      {
        title: "Booking Lead Time",
        amount: "30 days",
        improve: "-2 days from last month",
        icon: "/img/dashboard/icons/3.svg",
        description: "Understand booking patterns to optimize availability.",
      },
      {
        title: "Guest Reviews",
        amount: "4.5/5",
        improve: "+0.1 from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Monitor guest satisfaction to improve service quality.",
      },
    ],
    reports: [
      {
        title: "Property Performance",
        amount: "$10,000",
        improve: "+12% from last quarter",
        icon: "/img/dashboard/icons/1.svg",
        description:
          "Identify high-performing properties to allocate resources effectively.",
      },
      {
        title: "Seasonal Trends",
        amount: "Summer Peak",
        improve: "↑25% bookings vs. winter",
        icon: "/img/dashboard/icons/2.svg",
        description: "Plan for seasonal variations in demand.",
      },
      {
        title: "Cancellation Reasons",
        amount: "10% weather",
        improve: "-3% from last quarter",
        icon: "/img/dashboard/icons/3.svg",
        description:
          "Understand reasons for cancellations to improve policies.",
      },
      {
        title: "Revenue Per Property",
        amount: "$5,000",
        improve: "+8% from last quarter",
        icon: "/img/dashboard/icons/4.svg",
        description: "Measure the profitability of individual properties.",
      },
    ],
  },
  spaces: {
    overview: [
      {
        title: "Venue Occupancy",
        amount: "65.8%",
        improve: "+7.3% from last month",
        icon: "/img/dashboard/icons/1.svg",
        description: "Percentage of time venue is booked",
      },
      {
        title: "Event Bookings",
        amount: "22",
        improve: "+4 from last month",
        icon: "/img/dashboard/icons/3.svg",
        description: "Number of events booked",
      },
      {
        title: "Avg Revenue/Event",
        amount: "$1,250.00",
        improve: "+5.2% from last month",
        icon: "/img/dashboard/icons/2.svg",
        description: "Average revenue per event",
      },
      {
        title: "Customer Retention",
        amount: "68.5%",
        improve: "+3.1% from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Percentage of repeat customers",
      },
    ],
    analytics: [
      {
        title: "Event Type Distribution",
        amount: "50% corporate",
        improve: "+5% from last quarter",
        icon: "/img/dashboard/icons/1.svg",
        description: "Identify popular event types to tailor offerings.",
      },
      {
        title: "Booking Frequency",
        amount: "20 bookings",
        improve: "+3 from last month",
        icon: "/img/dashboard/icons/2.svg",
        description: "Track booking patterns to optimize availability.",
      },
      {
        title: "Capacity Utilization",
        amount: "80%",
        improve: "+7% from last quarter",
        icon: "/img/dashboard/icons/3.svg",
        description: "Higher utilization indicates better use of venue space.",
      },
      {
        title: "Cancellation Rate",
        amount: "5%",
        improve: "-2% from last quarter",
        icon: "/img/dashboard/icons/4.svg",
        description: "Monitor cancellations to identify potential issues.",
      },
    ],
    reports: [
      {
        title: "Venue Popularity",
        amount: "Venue A",
        improve: "↑2 positions",
        icon: "/img/dashboard/icons/1.svg",
        description:
          "Identify popular venues to allocate resources effectively.",
      },
      {
        title: "Seasonal Demand",
        amount: "Summer peak",
        improve: "↑35% vs winter",
        icon: "/img/dashboard/icons/2.svg",
        description: "Plan for seasonal variations in demand.",
      },
      {
        title: "Revenue by Event Type",
        amount: "$10,000",
        improve: "+15% from last quarter",
        icon: "/img/dashboard/icons/3.svg",
        description: "Measure revenue generated by different event types.",
      },
      {
        title: "Customer Demographics",
        amount: "60% corporate",
        improve: "+8% from last year",
        icon: "/img/dashboard/icons/4.svg",
        description:
          "Understand customer demographics to tailor marketing efforts.",
      },
    ],
  },
  activity: {
    overview: [
      {
        title: "Conversion Rate",
        amount: "9.3%",
        improve: "+2.1% from last month",
        icon: "/img/dashboard/icons/1.svg",
        description: "Percentage of visitors who book",
      },
      {
        title: "Attendance Rate",
        amount: "91.2%",
        improve: "+2.8% from last month",
        icon: "/img/dashboard/icons/3.svg",
        description: "Percentage of booked spots attended",
      },
      {
        title: "Revenue/Activity",
        amount: "$420.00",
        improve: "+5.7% from last month",
        icon: "/img/dashboard/icons/2.svg",
        description: "Average revenue per activity",
      },
      {
        title: "Avg Rating",
        amount: "4.8/5",
        improve: "+0.3 from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Average customer rating",
      },
    ],
    analytics: [
      {
        title: "Participant Count",
        amount: "100",
        improve: "+15 from last month",
        icon: "/img/dashboard/icons/1.svg",
        description: "Track participation to gauge popularity.",
      },
      {
        title: "Tour Ratings",
        amount: "4.8/5",
        improve: "+0.2 from last month",
        icon: "/img/dashboard/icons/2.svg",
        description: "Monitor tour ratings to improve service quality.",
      },
      {
        title: "Guide Performance",
        amount: "4.9/5",
        improve: "+0.1 from last month",
        icon: "/img/dashboard/icons/3.svg",
        description: "Evaluate guide performance to ensure quality.",
      },
      {
        title: "No-Show Rate",
        amount: "5%",
        improve: "-1% from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Monitor no-shows to identify potential issues.",
      },
    ],
    reports: [
      {
        title: "Tour Profitability",
        amount: "$5,000",
        improve: "+10% from last quarter",
        icon: "/img/dashboard/icons/1.svg",
        description: "Measure the profitability of individual tours.",
      },
      {
        title: "Guide Feedback",
        amount: "90% positive",
        improve: "+5% from last quarter",
        icon: "/img/dashboard/icons/2.svg",
        description: "Monitor guide feedback to ensure quality.",
      },
      {
        title: "Seasonal Activity Trends",
        amount: "Summer Peak",
        improve: "↑30% vs. winter",
        icon: "/img/dashboard/icons/3.svg",
        description: "Plan for seasonal variations in demand.",
      },
      {
        title: "Booking Channels",
        amount: "50% OTA",
        improve: "+8% from last quarter",
        icon: "/img/dashboard/icons/4.svg",
        description: "Identify key booking channels to optimize marketing.",
      },
    ],
  },
  event: {
    overview: [
      {
        title: "Venue Occupancy",
        amount: "65.8%",
        improve: "+7.3% from last month",
        icon: "/img/dashboard/icons/1.svg",
        description: "Percentage of time venue is booked",
      },
      {
        title: "Event Bookings",
        amount: "22",
        improve: "+4 from last month",
        icon: "/img/dashboard/icons/3.svg",
        description: "Number of events booked",
      },
      {
        title: "Avg Revenue/Event",
        amount: "$1,250.00",
        improve: "+5.2% from last month",
        icon: "/img/dashboard/icons/2.svg",
        description: "Average revenue per event",
      },
      {
        title: "Customer Retention",
        amount: "68.5%",
        improve: "+3.1% from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Percentage of repeat customers",
      },
    ],
    analytics: [
      {
        title: "Event Type Distribution",
        amount: "50% corporate",
        improve: "+5% from last quarter",
        icon: "/img/dashboard/icons/1.svg",
        description: "Identify popular event types to tailor offerings.",
      },
      {
        title: "Booking Frequency",
        amount: "20 bookings",
        improve: "+3 from last month",
        icon: "/img/dashboard/icons/2.svg",
        description: "Track booking patterns to optimize availability.",
      },
      {
        title: "Capacity Utilization",
        amount: "80%",
        improve: "+7% from last quarter",
        icon: "/img/dashboard/icons/3.svg",
        description: "Higher utilization indicates better use of venue space.",
      },
      {
        title: "Cancellation Rate",
        amount: "5%",
        improve: "-2% from last quarter",
        icon: "/img/dashboard/icons/4.svg",
        description: "Monitor cancellations to identify potential issues.",
      },
    ],
    reports: [
      {
        title: "Venue Popularity",
        amount: "Venue A",
        improve: "↑2 positions",
        icon: "/img/dashboard/icons/1.svg",
        description:
          "Identify popular venues to allocate resources effectively.",
      },
      {
        title: "Seasonal Demand",
        amount: "Summer peak",
        improve: "↑35% vs winter",
        icon: "/img/dashboard/icons/2.svg",
        description: "Plan for seasonal variations in demand.",
      },
      {
        title: "Revenue by Event Type",
        amount: "$10,000",
        improve: "+15% from last quarter",
        icon: "/img/dashboard/icons/3.svg",
        description: "Measure revenue generated by different event types.",
      },
      {
        title: "Customer Demographics",
        amount: "60% corporate",
        improve: "+8% from last year",
        icon: "/img/dashboard/icons/4.svg",
        description:
          "Understand customer demographics to tailor marketing efforts.",
      },
    ],
  },
  venue: {
    overview: [
      {
        title: "Venue Occupancy",
        amount: "65.8%",
        improve: "+7.3% from last month",
        icon: "/img/dashboard/icons/1.svg",
        description: "Percentage of time venue is booked",
      },
      {
        title: "Event Bookings",
        amount: "22",
        improve: "+4 from last month",
        icon: "/img/dashboard/icons/3.svg",
        description: "Number of events booked",
      },
      {
        title: "Avg Revenue/Event",
        amount: "$1,250.00",
        improve: "+5.2% from last month",
        icon: "/img/dashboard/icons/2.svg",
        description: "Average revenue per event",
      },
      {
        title: "Customer Retention",
        amount: "68.5%",
        improve: "+3.1% from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Percentage of repeat customers",
      },
    ],
    analytics: [
      {
        title: "Event Type Distribution",
        amount: "50% corporate",
        improve: "+5% from last quarter",
        icon: "/img/dashboard/icons/1.svg",
        description: "Identify popular event types to tailor offerings.",
      },
      {
        title: "Booking Frequency",
        amount: "20 bookings",
        improve: "+3 from last month",
        icon: "/img/dashboard/icons/2.svg",
        description: "Track booking patterns to optimize availability.",
      },
      {
        title: "Capacity Utilization",
        amount: "80%",
        improve: "+7% from last quarter",
        icon: "/img/dashboard/icons/3.svg",
        description: "Higher utilization indicates better use of venue space.",
      },
      {
        title: "Cancellation Rate",
        amount: "5%",
        improve: "-2% from last quarter",
        icon: "/img/dashboard/icons/4.svg",
        description: "Monitor cancellations to identify potential issues.",
      },
    ],
    reports: [
      {
        title: "Venue Popularity",
        amount: "Venue A",
        improve: "↑2 positions",
        icon: "/img/dashboard/icons/1.svg",
        description:
          "Identify popular venues to allocate resources effectively.",
      },
      {
        title: "Seasonal Demand",
        amount: "Summer peak",
        improve: "↑35% vs winter",
        icon: "/img/dashboard/icons/2.svg",
        description: "Plan for seasonal variations in demand.",
      },
      {
        title: "Revenue by Event Type",
        amount: "$10,000",
        improve: "+15% from last quarter",
        icon: "/img/dashboard/icons/3.svg",
        description: "Measure revenue generated by different event types.",
      },
      {
        title: "Customer Demographics",
        amount: "60% corporate",
        improve: "+8% from last year",
        icon: "/img/dashboard/icons/4.svg",
        description:
          "Understand customer demographics to tailor marketing efforts.",
      },
    ],
  },
  hotel: {
    overview: [
      {
        title: "Occupancy Rate",
        amount: "78.5%",
        improve: "+5.2% from last month",
        icon: "/img/dashboard/icons/1.svg",
        description: "Percentage of available rooms occupied",
      },
      {
        title: "Average Daily Rate",
        amount: "$189.50",
        improve: "+3.8% from last month",
        icon: "/img/dashboard/icons/3.svg",
        description: "Average revenue per occupied room",
      },
      {
        title: "RevPAR",
        amount: "$148.75",
        improve: "+9.1% from last month",
        icon: "/img/dashboard/icons/2.svg",
        description: "Revenue per available room",
      },
      {
        title: "Average Rating",
        amount: "4.7/5",
        improve: "+0.2 from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Average customer rating",
      },
    ],
    analytics: [
      {
        title: "Room Occupancy",
        amount: "80%",
        improve: "+2.5% from last month",
        icon: "/img/dashboard/icons/1.svg",
        description:
          "Higher occupancy indicates better utilization of hotel capacity.",
      },
      {
        title: "RevPAR",
        amount: "$100",
        improve: "+7.3% from last month",
        icon: "/img/dashboard/icons/2.svg",
        description: "Revenue generated per available room.",
      },
      {
        title: "ADR",
        amount: "$120",
        improve: "+4.1% from last month",
        icon: "/img/dashboard/icons/3.svg",
        description: "Average daily rate to ensure competitiveness.",
      },
      {
        title: "OTA Bookings",
        amount: "50%",
        improve: "+3.8% from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Percentage of bookings from Online Travel Agencies.",
      },
    ],
    reports: [
      {
        title: "Hotel Ranking",
        amount: "Ranked #1",
        improve: "↑2 ranks from last month",
        icon: "/img/dashboard/icons/1.svg",
        description: "Current position in customer satisfaction rankings.",
      },
      {
        title: "Guest Satisfaction",
        amount: "4.7/5",
        improve: "+0.3 from last month",
        icon: "/img/dashboard/icons/2.svg",
        description: "Average rating from guest reviews.",
      },
      {
        title: "Competitor Occupancy Gap",
        amount: "+10%",
        improve: "+2% from last month",
        icon: "/img/dashboard/icons/3.svg",
        description: "Occupancy rate vs. local competitors.",
      },
      {
        title: "Loyalty Program Revenue",
        amount: "20%",
        improve: "+5% from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Revenue uplift from loyalty members.",
      },
    ],
  },
  tour: {
    overview: [
      {
        title: "Conversion Rate",
        amount: "8.7%",
        improve: "+1.2% from last month",
        icon: "/img/dashboard/icons/1.svg",
        description: "Percentage of visitors who book",
      },
      {
        title: "Occupancy Rate",
        amount: "82.4%",
        improve: "+6.5% from last month",
        icon: "/img/dashboard/icons/3.svg",
        description: "Percentage of tour spots booked",
      },
      {
        title: "Revenue per Tour",
        amount: "$560.00",
        improve: "+4.8% from last month",
        icon: "/img/dashboard/icons/2.svg",
        description: "Average revenue per tour",
      },
      {
        title: "Cancellation Rate",
        amount: "4.2%",
        improve: "-1.5% from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Percentage of tours canceled",
      },
    ],
    analytics: [
      {
        title: "Participant Count",
        amount: "100",
        improve: "+15 from last month",
        icon: "/img/dashboard/icons/1.svg",
        description: "Track participation to gauge popularity.",
      },
      {
        title: "Tour Ratings",
        amount: "4.8/5",
        improve: "+0.2 from last month",
        icon: "/img/dashboard/icons/2.svg",
        description: "Monitor tour ratings to improve service quality.",
      },
      {
        title: "Guide Performance",
        amount: "4.9/5",
        improve: "+0.1 from last month",
        icon: "/img/dashboard/icons/3.svg",
        description: "Evaluate guide performance to ensure quality.",
      },
      {
        title: "No-Show Rate",
        amount: "5%",
        improve: "-1% from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Monitor no-shows to identify potential issues.",
      },
    ],
    reports: [
      {
        title: "Tour Profitability",
        amount: "$5,000",
        improve: "+10% from last quarter",
        icon: "/img/dashboard/icons/1.svg",
        description: "Measure the profitability of individual tours.",
      },
      {
        title: "Guide Feedback",
        amount: "90% positive",
        improve: "+5% from last quarter",
        icon: "/img/dashboard/icons/2.svg",
        description: "Monitor guide feedback to ensure quality.",
      },
      {
        title: "Seasonal Activity Trends",
        amount: "Summer Peak",
        improve: "↑30% vs. winter",
        icon: "/img/dashboard/icons/3.svg",
        description: "Plan for seasonal variations in demand.",
      },
      {
        title: "Booking Channels",
        amount: "50% OTA",
        improve: "+8% from last quarter",
        icon: "/img/dashboard/icons/4.svg",
        description: "Identify key booking channels to optimize marketing.",
      },
    ],
  },
  rides: {
    overview: [
      {
        title: "Venue Occupancy",
        amount: "65.8%",
        improve: "+7.3% from last month",
        icon: "/img/dashboard/icons/1.svg",
        description: "Percentage of time venue is booked",
      },
      {
        title: "Event Bookings",
        amount: "22",
        improve: "+4 from last month",
        icon: "/img/dashboard/icons/3.svg",
        description: "Number of events booked",
      },
      {
        title: "Avg Revenue/Event",
        amount: "$1,250.00",
        improve: "+5.2% from last month",
        icon: "/img/dashboard/icons/2.svg",
        description: "Average revenue per event",
      },
      {
        title: "Customer Retention",
        amount: "68.5%",
        improve: "+3.1% from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Percentage of repeat customers",
      },
    ],
    analytics: [
      {
        title: "Event Type Distribution",
        amount: "50% corporate",
        improve: "+5% from last quarter",
        icon: "/img/dashboard/icons/1.svg",
        description: "Identify popular event types to tailor offerings.",
      },
      {
        title: "Booking Frequency",
        amount: "20 bookings",
        improve: "+3 from last month",
        icon: "/img/dashboard/icons/2.svg",
        description: "Track booking patterns to optimize availability.",
      },
      {
        title: "Capacity Utilization",
        amount: "80%",
        improve: "+7% from last quarter",
        icon: "/img/dashboard/icons/3.svg",
        description: "Higher utilization indicates better use of venue space.",
      },
      {
        title: "Cancellation Rate",
        amount: "5%",
        improve: "-2% from last quarter",
        icon: "/img/dashboard/icons/4.svg",
        description: "Monitor cancellations to identify potential issues.",
      },
    ],
    reports: [
      {
        title: "Venue Popularity",
        amount: "Venue A",
        improve: "↑2 positions",
        icon: "/img/dashboard/icons/1.svg",
        description:
          "Identify popular venues to allocate resources effectively.",
      },
      {
        title: "Seasonal Demand",
        amount: "Summer peak",
        improve: "↑35% vs winter",
        icon: "/img/dashboard/icons/2.svg",
        description: "Plan for seasonal variations in demand.",
      },
      {
        title: "Revenue by Event Type",
        amount: "$10,000",
        improve: "+15% from last quarter",
        icon: "/img/dashboard/icons/3.svg",
        description: "Measure revenue generated by different event types.",
      },
      {
        title: "Customer Demographics",
        amount: "60% corporate",
        improve: "+8% from last year",
        icon: "/img/dashboard/icons/4.svg",
        description:
          "Understand customer demographics to tailor marketing efforts.",
      },
    ],
  },
  flights: {
    overview: [
      {
        title: "Venue Occupancy",
        amount: "65.8%",
        improve: "+7.3% from last month",
        icon: "/img/dashboard/icons/1.svg",
        description: "Percentage of time venue is booked",
      },
      {
        title: "Event Bookings",
        amount: "22",
        improve: "+4 from last month",
        icon: "/img/dashboard/icons/3.svg",
        description: "Number of events booked",
      },
      {
        title: "Avg Revenue/Event",
        amount: "$1,250.00",
        improve: "+5.2% from last month",
        icon: "/img/dashboard/icons/2.svg",
        description: "Average revenue per event",
      },
      {
        title: "Customer Retention",
        amount: "68.5%",
        improve: "+3.1% from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Percentage of repeat customers",
      },
    ],
    analytics: [
      {
        title: "Event Type Distribution",
        amount: "50% corporate",
        improve: "+5% from last quarter",
        icon: "/img/dashboard/icons/1.svg",
        description: "Identify popular event types to tailor offerings.",
      },
      {
        title: "Booking Frequency",
        amount: "20 bookings",
        improve: "+3 from last month",
        icon: "/img/dashboard/icons/2.svg",
        description: "Track booking patterns to optimize availability.",
      },
      {
        title: "Capacity Utilization",
        amount: "80%",
        improve: "+7% from last quarter",
        icon: "/img/dashboard/icons/3.svg",
        description: "Higher utilization indicates better use of venue space.",
      },
      {
        title: "Cancellation Rate",
        amount: "5%",
        improve: "-2% from last quarter",
        icon: "/img/dashboard/icons/4.svg",
        description: "Monitor cancellations to identify potential issues.",
      },
    ],
    reports: [
      {
        title: "Venue Popularity",
        amount: "Venue A",
        improve: "↑2 positions",
        icon: "/img/dashboard/icons/1.svg",
        description:
          "Identify popular venues to allocate resources effectively.",
      },
      {
        title: "Seasonal Demand",
        amount: "Summer peak",
        improve: "↑35% vs winter",
        icon: "/img/dashboard/icons/2.svg",
        description: "Plan for seasonal variations in demand.",
      },
      {
        title: "Revenue by Event Type",
        amount: "$10,000",
        improve: "+15% from last quarter",
        icon: "/img/dashboard/icons/3.svg",
        description: "Measure revenue generated by different event types.",
      },
      {
        title: "Customer Demographics",
        amount: "60% corporate",
        improve: "+8% from last year",
        icon: "/img/dashboard/icons/4.svg",
        description:
          "Understand customer demographics to tailor marketing efforts.",
      },
    ],
  },
};

export default dashboardData;
