const dashboardData = {
  overview: [
    {
      title: "Total Sales",
      amount: "$24,231.89",
      improve: "+15.2% from last month",
      icon: "/img/dashboard/icons/1.svg",
    },
    {
      title: "Total Bookings",
      amount: "432",
      improve: "+8.2% from last month",
      icon: "/img/dashboard/icons/3.svg",
    },
    {
      title: "Net Earnings",
      amount: "$18,565.00",
      improve: "+12.5% from last month",
      icon: "/img/dashboard/icons/2.svg",
    },
    {
      title: "Active Listings",
      amount: "12",
      improve: "+2 new listings this month",
      icon: "/img/dashboard/icons/4.svg",
    },
  ],
  vacation: [
    {
      title: "Occupancy Rate",
      amount: "72.3%",
      improve: "+4.1% from last month",
      icon: "/img/dashboard/icons/1.svg",
      description: "Percentage of nights booked",
    },
    {
      title: "Avg Length of Stay",
      amount: "4.2 days",
      improve: "+0.5 days from last month",
      icon: "/img/dashboard/icons/3.svg",
      description: "Average duration of guest stays",
    },
    {
      title: "Net Revenue",
      amount: "$18,565.00",
      improve: "+12.6% from last month",
      icon: "/img/dashboard/icons/2.svg",
      description: "Revenue after fees and expenses",
    },
    {
      title: "Booking Window",
      amount: "38 days",
      improve: "+5 days from last month",
      icon: "/img/dashboard/icons/4.svg",
      description: "Average time between booking and check-in",
    },
  ],
  attraction: [
    {
      title: "Conversion Rate",
      amount: "9.3%",
      improve: "+2.1% from last month",
      icon: "/img/dashboard/icons/1.svg",
      description: "Percentage of visitors who book",
    },
    {
      title: "Attendance Rate",
      amount: "91.2%",
      improve: "+2.8% from last month",
      icon: "/img/dashboard/icons/3.svg",
      description: "Percentage of booked spots attended",
    },
    {
      title: "Revenue/Activity",
      amount: "$420.00",
      improve: "+5.7% from last month",
      icon: "/img/dashboard/icons/2.svg",
      description: "Average revenue per activity",
    },
    {
      title: "Avg Rating",
      amount: "4.8/5",
      improve: "+0.3 from last month",
      icon: "/img/dashboard/icons/4.svg",
      description: "Average customer rating",
    },
  ],
  event: [
    {
      title: "Venue Occupancy",
      amount: "65.8%",
      improve: "+7.3% from last month",
      icon: "/img/dashboard/icons/1.svg",
      description: "Percentage of time venue is booked",
    },
    {
      title: "Event Bookings",
      amount: "22",
      improve: "+4 from last month",
      icon: "/img/dashboard/icons/3.svg",
      description: "Number of events booked",
    },
    {
      title: "Avg Revenue/Event",
      amount: "$1,250.00",
      improve: "+5.2% from last month",
      icon: "/img/dashboard/icons/2.svg",
      description: "Average revenue per event",
    },
    {
      title: "Customer Retention",
      amount: "68.5%",
      improve: "+3.1% from last month",
      icon: "/img/dashboard/icons/4.svg",
      description: "Percentage of repeat customers",
    },
  ],
  property: [
    {
      title: "Occupancy Rate",
      amount: "78.5%",
      improve: "+5.2% from last month",
      icon: "/img/dashboard/icons/1.svg",
      description: "Percentage of available rooms occupied",
    },
    {
      title: "Average Daily Rate",
      amount: "$189.50",
      improve: "+3.8% from last month",
      icon: "/img/dashboard/icons/3.svg",
      description: "Average revenue per occupied room",
    },
    {
      title: "RevPAR",
      amount: "$148.75",
      improve: "+9.1% from last month",
      icon: "/img/dashboard/icons/2.svg",
      description: "Revenue per available room",
    },
    {
      title: "Average Rating",
      amount: "4.7/5",
      improve: "+0.2 from last month",
      icon: "/img/dashboard/icons/4.svg",
      description: "Average customer rating",
    },
  ],
  tour: [
    {
      title: "Conversion Rate",
      amount: "8.7%",
      improve: "+1.2% from last month",
      icon: "/img/dashboard/icons/1.svg",
      description: "Percentage of visitors who book",
    },
    {
      title: "Occupancy Rate",
      amount: "82.4%",
      improve: "+6.5% from last month",
      icon: "/img/dashboard/icons/3.svg",
      description: "Percentage of tour spots booked",
    },
    {
      title: "Revenue per Tour",
      amount: "$560.00",
      improve: "+4.8% from last month",
      icon: "/img/dashboard/icons/2.svg",
      description: "Average revenue per tour",
    },
    {
      title: "Cancellation Rate",
      amount: "4.2%",
      improve: "-1.5% from last month",
      icon: "/img/dashboard/icons/4.svg",
      description: "Percentage of tours canceled",
    },
  ],
};

export default dashboardData;
