const dashboardData = {
  vacation: {
    overview: [
      {
        title: "GMV",
        amount: "$1,000,000 GMV in Q1",
        improve: "+4.1% from last month",
        icon: "/img/dashboard/icons/1.svg",
        description: "Total value of transactions",
      },
      {
        title: "Active users",
        amount: "1000 active users",
        improve: "+0.5 days from last month",
        icon: "/img/dashboard/icons/3.svg",
        description: "Number of active users",
      },
      {
        title: "Booking volume by category",
        amount: "500 bookings in Vacation",
        improve: "+12.6% from last month",
        icon: "/img/dashboard/icons/2.svg",
        description: "Booking volume",
      },
      {
        title: "CAC",
        amount: "$50 CAC",
        improve: "+5 CAC from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Cost of acquiring new customers.",
      },
      {
        title: "Churn rate",
        amount: "5% churn rate",
        improve: "+0.2% from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Rate of user attrition.",
      },
      {
        title: "NPS",
        amount: "NPS of 70",
        improve: "+5 from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Customer satisfaction and loyalty.",
      },
    ],
    analytics: [
      {
        title: "Occupancy Rate",
        amount: "75%",
        improve: "+3.2% from last month",
        icon: "/img/dashboard/icons/1.svg",
        description:
          "Higher occupancy indicates better utilization of properties.",
      },
      {
        title: "Average Nightly Rate",
        amount: "$150",
        improve: "+5.1% from last month",
        icon: "/img/dashboard/icons/2.svg",
        description: "Track pricing to ensure competitiveness.",
      },
      {
        title: "Booking Lead Time",
        amount: "30 days",
        improve: "-2 days from last month",
        icon: "/img/dashboard/icons/3.svg",
        description: "Understand booking patterns to optimize availability.",
      },
      {
        title: "Guest Reviews",
        amount: "4.5/5",
        improve: "+0.1 from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Monitor guest satisfaction to improve service quality.",
      },
    ],
    reports: [
      {
        title: "Property Performance",
        amount: "$10,000",
        improve: "+12% from last quarter",
        icon: "/img/dashboard/icons/1.svg",
        description:
          "Identify high-performing properties to allocate resources effectively.",
      },
      {
        title: "Seasonal Trends",
        amount: "Summer Peak",
        improve: "↑25% bookings vs. winter",
        icon: "/img/dashboard/icons/2.svg",
        description: "Plan for seasonal variations in demand.",
      },
      {
        title: "Cancellation Reasons",
        amount: "10% weather",
        improve: "-3% from last quarter",
        icon: "/img/dashboard/icons/3.svg",
        description:
          "Understand reasons for cancellations to improve policies.",
      },
      {
        title: "Revenue Per Property",
        amount: "$5,000",
        improve: "+8% from last quarter",
        icon: "/img/dashboard/icons/4.svg",
        description: "Measure the profitability of individual properties.",
      },
    ],
  },
  spaces: {
    overview: [
      {
        title: "GMV",
        amount: "$1,000,000 GMV in Q1",
        improve: "+4.1% from last month",
        icon: "/img/dashboard/icons/1.svg",
        description: "Total value of transactions",
      },
      {
        title: "Active users",
        amount: "1000 active users",
        improve: "+0.5 days from last month",
        icon: "/img/dashboard/icons/3.svg",
        description: "Number of active users",
      },
      {
        title: "Booking volume by category",
        amount: "500 bookings in Spaces",
        improve: "+12.6% from last month",
        icon: "/img/dashboard/icons/2.svg",
        description: "Booking volume",
      },
      {
        title: "CAC",
        amount: "$50 CAC",
        improve: "+5 CAC from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Cost of acquiring new customers.",
      },
      {
        title: "Churn rate",
        amount: "5% churn rate",
        improve: "+0.2% from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Rate of user attrition.",
      },
      {
        title: "NPS",
        amount: "NPS of 70",
        improve: "+5 from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Customer satisfaction and loyalty.",
      },
    ],
    analytics: [
      {
        title: "Event Type Distribution",
        amount: "50% corporate",
        improve: "+5% from last quarter",
        icon: "/img/dashboard/icons/1.svg",
        description: "Identify popular event types to tailor offerings.",
      },
      {
        title: "Booking Frequency",
        amount: "20 bookings",
        improve: "+3 from last month",
        icon: "/img/dashboard/icons/2.svg",
        description: "Track booking patterns to optimize availability.",
      },
      {
        title: "Capacity Utilization",
        amount: "80%",
        improve: "+7% from last quarter",
        icon: "/img/dashboard/icons/3.svg",
        description: "Higher utilization indicates better use of venue space.",
      },
      {
        title: "Cancellation Rate",
        amount: "5%",
        improve: "-2% from last quarter",
        icon: "/img/dashboard/icons/4.svg",
        description: "Monitor cancellations to identify potential issues.",
      },
    ],
    reports: [
      {
        title: "Venue Popularity",
        amount: "Venue A",
        improve: "↑2 positions",
        icon: "/img/dashboard/icons/1.svg",
        description:
          "Identify popular venues to allocate resources effectively.",
      },
      {
        title: "Seasonal Demand",
        amount: "Summer peak",
        improve: "↑35% vs winter",
        icon: "/img/dashboard/icons/2.svg",
        description: "Plan for seasonal variations in demand.",
      },
      {
        title: "Revenue by Event Type",
        amount: "$10,000",
        improve: "+15% from last quarter",
        icon: "/img/dashboard/icons/3.svg",
        description: "Measure revenue generated by different event types.",
      },
      {
        title: "Customer Demographics",
        amount: "60% corporate",
        improve: "+8% from last year",
        icon: "/img/dashboard/icons/4.svg",
        description:
          "Understand customer demographics to tailor marketing efforts.",
      },
    ],
  },
  activity: {
    overview: [
      {
        title: "GMV",
        amount: "$1,000,000 GMV in Q1",
        improve: "+4.1% from last month",
        icon: "/img/dashboard/icons/1.svg",
        description: "Total value of transactions",
      },
      {
        title: "Active users",
        amount: "1000 active users",
        improve: "+0.5 days from last month",
        icon: "/img/dashboard/icons/3.svg",
        description: "Number of active users",
      },
      {
        title: "Booking volume by category",
        amount: "500 bookings in Activity",
        improve: "+12.6% from last month",
        icon: "/img/dashboard/icons/2.svg",
        description: "Booking volume",
      },
      {
        title: "CAC",
        amount: "$50 CAC",
        improve: "+5 CAC from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Cost of acquiring new customers.",
      },
      {
        title: "Churn rate",
        amount: "5% churn rate",
        improve: "+0.2% from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Rate of user attrition.",
      },
      {
        title: "NPS",
        amount: "NPS of 70",
        improve: "+5 from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Customer satisfaction and loyalty.",
      },
    ],
    analytics: [
      {
        title: "Participant Count",
        amount: "100",
        improve: "+15 from last month",
        icon: "/img/dashboard/icons/1.svg",
        description: "Track participation to gauge popularity.",
      },
      {
        title: "Tour Ratings",
        amount: "4.8/5",
        improve: "+0.2 from last month",
        icon: "/img/dashboard/icons/2.svg",
        description: "Monitor tour ratings to improve service quality.",
      },
      {
        title: "Guide Performance",
        amount: "4.9/5",
        improve: "+0.1 from last month",
        icon: "/img/dashboard/icons/3.svg",
        description: "Evaluate guide performance to ensure quality.",
      },
      {
        title: "No-Show Rate",
        amount: "5%",
        improve: "-1% from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Monitor no-shows to identify potential issues.",
      },
    ],
    reports: [
      {
        title: "Tour Profitability",
        amount: "$5,000",
        improve: "+10% from last quarter",
        icon: "/img/dashboard/icons/1.svg",
        description: "Measure the profitability of individual tours.",
      },
      {
        title: "Guide Feedback",
        amount: "90% positive",
        improve: "+5% from last quarter",
        icon: "/img/dashboard/icons/2.svg",
        description: "Monitor guide feedback to ensure quality.",
      },
      {
        title: "Seasonal Activity Trends",
        amount: "Summer Peak",
        improve: "↑30% vs. winter",
        icon: "/img/dashboard/icons/3.svg",
        description: "Plan for seasonal variations in demand.",
      },
      {
        title: "Booking Channels",
        amount: "50% OTA",
        improve: "+8% from last quarter",
        icon: "/img/dashboard/icons/4.svg",
        description: "Identify key booking channels to optimize marketing.",
      },
    ],
  },
  event: {
    overview: [
      {
        title: "GMV",
        amount: "$1,000,000 GMV in Q1",
        improve: "+4.1% from last month",
        icon: "/img/dashboard/icons/1.svg",
        description: "Total value of transactions",
      },
      {
        title: "Active users",
        amount: "1000 active users",
        improve: "+0.5 days from last month",
        icon: "/img/dashboard/icons/3.svg",
        description: "Number of active users",
      },
      {
        title: "Booking volume by category",
        amount: "500 bookings in Event",
        improve: "+12.6% from last month",
        icon: "/img/dashboard/icons/2.svg",
        description: "Booking volume",
      },
      {
        title: "CAC",
        amount: "$50 CAC",
        improve: "+5 CAC from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Cost of acquiring new customers.",
      },
      {
        title: "Churn rate",
        amount: "5% churn rate",
        improve: "+0.2% from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Rate of user attrition.",
      },
      {
        title: "NPS",
        amount: "NPS of 70",
        improve: "+5 from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Customer satisfaction and loyalty.",
      },
    ],
    analytics: [
      {
        title: "Event Type Distribution",
        amount: "50% corporate",
        improve: "+5% from last quarter",
        icon: "/img/dashboard/icons/1.svg",
        description: "Identify popular event types to tailor offerings.",
      },
      {
        title: "Booking Frequency",
        amount: "20 bookings",
        improve: "+3 from last month",
        icon: "/img/dashboard/icons/2.svg",
        description: "Track booking patterns to optimize availability.",
      },
      {
        title: "Capacity Utilization",
        amount: "80%",
        improve: "+7% from last quarter",
        icon: "/img/dashboard/icons/3.svg",
        description: "Higher utilization indicates better use of venue space.",
      },
      {
        title: "Cancellation Rate",
        amount: "5%",
        improve: "-2% from last quarter",
        icon: "/img/dashboard/icons/4.svg",
        description: "Monitor cancellations to identify potential issues.",
      },
    ],
    reports: [
      {
        title: "Venue Popularity",
        amount: "Venue A",
        improve: "↑2 positions",
        icon: "/img/dashboard/icons/1.svg",
        description:
          "Identify popular venues to allocate resources effectively.",
      },
      {
        title: "Seasonal Demand",
        amount: "Summer peak",
        improve: "↑35% vs winter",
        icon: "/img/dashboard/icons/2.svg",
        description: "Plan for seasonal variations in demand.",
      },
      {
        title: "Revenue by Event Type",
        amount: "$10,000",
        improve: "+15% from last quarter",
        icon: "/img/dashboard/icons/3.svg",
        description: "Measure revenue generated by different event types.",
      },
      {
        title: "Customer Demographics",
        amount: "60% corporate",
        improve: "+8% from last year",
        icon: "/img/dashboard/icons/4.svg",
        description:
          "Understand customer demographics to tailor marketing efforts.",
      },
    ],
  },
  venue: {
    overview: [
      {
        title: "GMV",
        amount: "$1,000,000 GMV in Q1",
        improve: "+4.1% from last month",
        icon: "/img/dashboard/icons/1.svg",
        description: "Total value of transactions",
      },
      {
        title: "Active users",
        amount: "1000 active users",
        improve: "+0.5 days from last month",
        icon: "/img/dashboard/icons/3.svg",
        description: "Number of active users",
      },
      {
        title: "Booking volume by category",
        amount: "500 bookings in Venue",
        improve: "+12.6% from last month",
        icon: "/img/dashboard/icons/2.svg",
        description: "Booking volume",
      },
      {
        title: "CAC",
        amount: "$50 CAC",
        improve: "+5 CAC from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Cost of acquiring new customers.",
      },
      {
        title: "Churn rate",
        amount: "5% churn rate",
        improve: "+0.2% from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Rate of user attrition.",
      },
      {
        title: "NPS",
        amount: "NPS of 70",
        improve: "+5 from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Customer satisfaction and loyalty.",
      },
    ],
    analytics: [
      {
        title: "Event Type Distribution",
        amount: "50% corporate",
        improve: "+5% from last quarter",
        icon: "/img/dashboard/icons/1.svg",
        description: "Identify popular event types to tailor offerings.",
      },
      {
        title: "Booking Frequency",
        amount: "20 bookings",
        improve: "+3 from last month",
        icon: "/img/dashboard/icons/2.svg",
        description: "Track booking patterns to optimize availability.",
      },
      {
        title: "Capacity Utilization",
        amount: "80%",
        improve: "+7% from last quarter",
        icon: "/img/dashboard/icons/3.svg",
        description: "Higher utilization indicates better use of venue space.",
      },
      {
        title: "Cancellation Rate",
        amount: "5%",
        improve: "-2% from last quarter",
        icon: "/img/dashboard/icons/4.svg",
        description: "Monitor cancellations to identify potential issues.",
      },
    ],
    reports: [
      {
        title: "Venue Popularity",
        amount: "Venue A",
        improve: "↑2 positions",
        icon: "/img/dashboard/icons/1.svg",
        description:
          "Identify popular venues to allocate resources effectively.",
      },
      {
        title: "Seasonal Demand",
        amount: "Summer peak",
        improve: "↑35% vs winter",
        icon: "/img/dashboard/icons/2.svg",
        description: "Plan for seasonal variations in demand.",
      },
      {
        title: "Revenue by Event Type",
        amount: "$10,000",
        improve: "+15% from last quarter",
        icon: "/img/dashboard/icons/3.svg",
        description: "Measure revenue generated by different event types.",
      },
      {
        title: "Customer Demographics",
        amount: "60% corporate",
        improve: "+8% from last year",
        icon: "/img/dashboard/icons/4.svg",
        description:
          "Understand customer demographics to tailor marketing efforts.",
      },
    ],
  },
  hotel: {
    overview: [
      {
        title: "GMV",
        amount: "$1,000,000 GMV in Q1",
        improve: "+4.1% from last month",
        icon: "/img/dashboard/icons/1.svg",
        description: "Total value of transactions",
      },
      {
        title: "Active users",
        amount: "1000 active users",
        improve: "+0.5 days from last month",
        icon: "/img/dashboard/icons/3.svg",
        description: "Number of active users",
      },
      {
        title: "Booking volume by category",
        amount: "500 bookings in Hotel",
        improve: "+12.6% from last month",
        icon: "/img/dashboard/icons/2.svg",
        description: "Booking volume",
      },
      {
        title: "CAC",
        amount: "$50 CAC",
        improve: "+5 CAC from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Cost of acquiring new customers.",
      },
      {
        title: "Churn rate",
        amount: "5% churn rate",
        improve: "+0.2% from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Rate of user attrition.",
      },
      {
        title: "NPS",
        amount: "NPS of 70",
        improve: "+5 from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Customer satisfaction and loyalty.",
      },
    ],
    analytics: [
      {
        title: "Room Occupancy",
        amount: "80%",
        improve: "+2.5% from last month",
        icon: "/img/dashboard/icons/1.svg",
        description:
          "Higher occupancy indicates better utilization of hotel capacity.",
      },
      {
        title: "RevPAR",
        amount: "$100",
        improve: "+7.3% from last month",
        icon: "/img/dashboard/icons/2.svg",
        description: "Revenue generated per available room.",
      },
      {
        title: "ADR",
        amount: "$120",
        improve: "+4.1% from last month",
        icon: "/img/dashboard/icons/3.svg",
        description: "Average daily rate to ensure competitiveness.",
      },
      {
        title: "OTA Bookings",
        amount: "50%",
        improve: "+3.8% from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Percentage of bookings from Online Travel Agencies.",
      },
    ],
    reports: [
      {
        title: "Hotel Ranking",
        amount: "Ranked #1",
        improve: "↑2 ranks from last month",
        icon: "/img/dashboard/icons/1.svg",
        description: "Current position in customer satisfaction rankings.",
      },
      {
        title: "Guest Satisfaction",
        amount: "4.7/5",
        improve: "+0.3 from last month",
        icon: "/img/dashboard/icons/2.svg",
        description: "Average rating from guest reviews.",
      },
      {
        title: "Competitor Occupancy Gap",
        amount: "+10%",
        improve: "+2% from last month",
        icon: "/img/dashboard/icons/3.svg",
        description: "Occupancy rate vs. local competitors.",
      },
      {
        title: "Loyalty Program Revenue",
        amount: "20%",
        improve: "+5% from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Revenue uplift from loyalty members.",
      },
    ],
  },
  tour: {
    overview: [
      {
        title: "GMV",
        amount: "$1,000,000 GMV in Q1",
        improve: "+4.1% from last month",
        icon: "/img/dashboard/icons/1.svg",
        description: "Total value of transactions",
      },
      {
        title: "Active users",
        amount: "1000 active users",
        improve: "+0.5 days from last month",
        icon: "/img/dashboard/icons/3.svg",
        description: "Number of active users",
      },
      {
        title: "Booking volume by category",
        amount: "500 bookings in Tour",
        improve: "+12.6% from last month",
        icon: "/img/dashboard/icons/2.svg",
        description: "Booking volume",
      },
      {
        title: "CAC",
        amount: "$50 CAC",
        improve: "+5 CAC from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Cost of acquiring new customers.",
      },
      {
        title: "Churn rate",
        amount: "5% churn rate",
        improve: "+0.2% from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Rate of user attrition.",
      },
      {
        title: "NPS",
        amount: "NPS of 70",
        improve: "+5 from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Customer satisfaction and loyalty.",
      },
    ],
    analytics: [
      {
        title: "Participant Count",
        amount: "100",
        improve: "+15 from last month",
        icon: "/img/dashboard/icons/1.svg",
        description: "Track participation to gauge popularity.",
      },
      {
        title: "Tour Ratings",
        amount: "4.8/5",
        improve: "+0.2 from last month",
        icon: "/img/dashboard/icons/2.svg",
        description: "Monitor tour ratings to improve service quality.",
      },
      {
        title: "Guide Performance",
        amount: "4.9/5",
        improve: "+0.1 from last month",
        icon: "/img/dashboard/icons/3.svg",
        description: "Evaluate guide performance to ensure quality.",
      },
      {
        title: "No-Show Rate",
        amount: "5%",
        improve: "-1% from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Monitor no-shows to identify potential issues.",
      },
    ],
    reports: [
      {
        title: "Tour Profitability",
        amount: "$5,000",
        improve: "+10% from last quarter",
        icon: "/img/dashboard/icons/1.svg",
        description: "Measure the profitability of individual tours.",
      },
      {
        title: "Guide Feedback",
        amount: "90% positive",
        improve: "+5% from last quarter",
        icon: "/img/dashboard/icons/2.svg",
        description: "Monitor guide feedback to ensure quality.",
      },
      {
        title: "Seasonal Activity Trends",
        amount: "Summer Peak",
        improve: "↑30% vs. winter",
        icon: "/img/dashboard/icons/3.svg",
        description: "Plan for seasonal variations in demand.",
      },
      {
        title: "Booking Channels",
        amount: "50% OTA",
        improve: "+8% from last quarter",
        icon: "/img/dashboard/icons/4.svg",
        description: "Identify key booking channels to optimize marketing.",
      },
    ],
  },
  rides: {
    overview: [
      {
        title: "GMV",
        amount: "$1,000,000 GMV in Q1",
        improve: "+4.1% from last month",
        icon: "/img/dashboard/icons/1.svg",
        description: "Total value of transactions",
      },
      {
        title: "Active users",
        amount: "1000 active users",
        improve: "+0.5 days from last month",
        icon: "/img/dashboard/icons/3.svg",
        description: "Number of active users",
      },
      {
        title: "Booking volume by category",
        amount: "500 bookings in Rides",
        improve: "+12.6% from last month",
        icon: "/img/dashboard/icons/2.svg",
        description: "Booking volume",
      },
      {
        title: "CAC",
        amount: "$50 CAC",
        improve: "+5 CAC from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Cost of acquiring new customers.",
      },
      {
        title: "Churn rate",
        amount: "5% churn rate",
        improve: "+0.2% from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Rate of user attrition.",
      },
      {
        title: "NPS",
        amount: "NPS of 70",
        improve: "+5 from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Customer satisfaction and loyalty.",
      },
    ],
    analytics: [
      {
        title: "Bookings by location",
        amount: "200 bookings at LAX",
        improve: "+4.1% from last month",
        icon: "/img/dashboard/icons/1.svg",
        description: "Identify high-demand locations to optimize fleet allocation.",
      },
      {
        title: "Vehicle type utilization",
        amount: "SUVs have 90% utilization rate",
        improve: "+0.5% from last month",
        icon: "/img/dashboard/icons/3.svg",
        description: "Track which vehicle types are most popular to adjust inventory.",
      },
      {
        title: "Average rental duration",
        amount: "3 days average",
        improve: "+12.6% from last month",
        icon: "/img/dashboard/icons/2.svg",
        description: "Understand rental patterns to improve customer offerings.",
      },
      {
        title: "Damage reports",
        amount: "5 damage reports",
        improve: "+2% from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Monitor damage incidents to manage maintenance and insurance costs.",
      },
    ],
    reports: [
      {
        title: "Fleet performance",
        amount: "Fleet utilization rate is 80%",
        improve: "+12% from last quarter",
        icon: "/img/dashboard/icons/1.svg",
        description:
          "Evaluate overall fleet performance to optimize operations.",
      },
      {
        title: "Location-wise demand",
        amount: "High demand at airport locations",
        improve: "↑25% bookings vs. winter",
        icon: "/img/dashboard/icons/2.svg",
        description: "Identify demand patterns to improve service availability.",
      },
      {
        title: "Maintenance schedules",
        amount: "50 vehicles due for maintenance in March",
        improve: "-3% from last quarter",
        icon: "/img/dashboard/icons/3.svg",
        description:
          "Plan maintenance activities to minimize downtime.",
      },
      {
        title: "Pricing trends",
        amount: "Average rental price increased by 5%",
        improve: "+8% from last quarter",
        icon: "/img/dashboard/icons/4.svg",
        description: "Track pricing trends to adjust rates competitively.",
      },
    ],
  },
  flights: {
    overview: [
      {
        title: "GMV",
        amount: "$1,000,000 GMV in Q1",
        improve: "+4.1% from last month",
        icon: "/img/dashboard/icons/1.svg",
        description: "Total value of transactions",
      },
      {
        title: "Active users",
        amount: "1000 active users",
        improve: "+0.5 days from last month",
        icon: "/img/dashboard/icons/3.svg",
        description: "Number of active users",
      },
      {
        title: "Booking volume by category",
        amount: "500 bookings in Flights",
        improve: "+12.6% from last month",
        icon: "/img/dashboard/icons/2.svg",
        description: "Booking volume",
      },
      {
        title: "CAC",
        amount: "$50 CAC",
        improve: "+5 CAC from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Cost of acquiring new customers.",
      },
      {
        title: "Churn rate",
        amount: "5% churn rate",
        improve: "+0.2% from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Rate of user attrition.",
      },
      {
        title: "NPS",
        amount: "NPS of 70",
        improve: "+5 from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Customer satisfaction and loyalty.",
      },
    ],
    analytics: [
      {
        title: "Bookings by route/date",
        amount: "1000 bookings on NYC-LAX route",
        improve: "+4.1% from last month",
        icon: "/img/dashboard/icons/1.svg",
        description: "Analyze which routes and dates are most popular to optimize scheduling and pricing.",
      },
      {
        title: "Seat occupancy",
        amount: "85% average seat occupancy",
        improve: "+0.5% from last month",
        icon: "/img/dashboard/icons/3.svg",
        description: "Higher occupancy indicates better utilization of flight capacity.",
      },
      {
        title: "Fare trends",
        amount: "Average fare increased by 5%",
        improve: "+12.6% from last Q",
        icon: "/img/dashboard/icons/2.svg",
        description: "Track fare changes to adjust pricing strategies.",
      },
      {
        title: "Cancellations",
        amount: "50 cancellations",
        improve: "+2% from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Monitor cancellation rates to identify potential issues and improve customer satisfaction.",
      },
      {
        title: "Revenue per flight",
        amount: "$50,000 revenue for flight AA123",
        improve: "+2% from last month",
        icon: "/img/dashboard/icons/4.svg",
        description: "Measure the profitability of individual flights.",
      },
    ],
    reports: [
      {
        title: "Route performance",
        amount: "NYC-LAX route generated $500,000",
        improve: "+12% from last Q",
        icon: "/img/dashboard/icons/1.svg",
        description:
          "Identify high-performing routes to allocate resources effectively.",
      },
      {
        title: "Seasonal demand",
        amount: "Peak demand in summer months",
        improve: "↑25% bookings vs. winter",
        icon: "/img/dashboard/icons/2.svg",
        description: "Plan for seasonal variations in demand.",
      },
      {
        title: "Fare optimization",
        amount: "Dynamic pricing increased revenue by 10%",
        improve: "-3% from last quarter",
        icon: "/img/dashboard/icons/3.svg",
        description:
          "Evaluate the effectiveness of fare optimization strategies.",
      },
      {
        title: "Partner airline comparison",
        amount: "Partner airline A has 10% higher occupancy",
        improve: "+8% from last quarter",
        icon: "/img/dashboard/icons/4.svg",
        description: "Compare performance with partner airlines to identify best practices.",
      },
    ],
  },
};

export default dashboardData;
